version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/token-generator-api/Dockerfile
      args:
        - PROJECT=@jventures-jdn/token-generator-api
    container_name: "token-generator-api"
    ports:
      - 4000:4000

